import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import '../../../components/buttons.dart';
import '../../../components/input_field.dart';
import '../../../constants/app_colors.dart';
import '../../../constants/app_fonts.dart';
import '../../../constants/app_images.dart';
import '../../../constants/app_routes.dart';
import '../../../utils/property_util/access_code_utils.dart';
import '../../../utils/tc.dart';

class Welcome extends StatefulWidget {
  const Welcome({Key? key}) : super(key: key);

  @override
  _WelcomeState createState() => _WelcomeState();
}

class _WelcomeState extends State<Welcome> {
  String code = '';
  final _codeFormKey = GlobalKey<FormState>();
  @override
  Widget build(BuildContext context) {
    SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
        statusBarColor: Colors.transparent, // transparent status bar
        statusBarIconBrightness: Brightness.light // dark text for status bar
        ));
    final _getSize = MediaQuery.of(context).size;
    return Scaffold(
        backgroundColor: Pallete.onboardColor,
        body: SingleChildScrollView(
          child: Container(
            child: Column(
              children: [
                Stack(children: [
                  Image.asset(AppImages.banner),
                  Positioned(
                    left: _getSize.width * 0.1,
                    bottom: _getSize.height * 0.15,
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          'Access Code',
                          style: AppFonts.boldText.copyWith(
                              fontWeight: FontWeight.bold,
                              color: Pallete.primaryColor,
                              fontSize: 20),
                        ),
                        SizedBox(
                          height: _getSize.height * 0.003,
                        ),
                        SizedBox(
                          width: _getSize.width * 0.7,
                          child: Text(
                            'Kindly provide an access code generated by your landlord in the text field.',
                            maxLines: 2,
                            style: AppFonts.bodyText.copyWith(
                                fontWeight: FontWeight.w300,
                                color: Pallete.whiteColor,
                                fontSize: 12),
                          ),
                        ),
                      ],
                    ),
                  ),
                ]),
                Padding(
                  padding:
                      const EdgeInsets.symmetric(horizontal: 32.0, vertical: 4),
                  child: Form(
                    key: _codeFormKey,
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          'What’s your access code?',
                          style: AppFonts.bodyText.copyWith(
                              fontWeight: FontWeight.w600,
                              color: Pallete.primaryColor,
                              fontSize: 20),
                        ),
                        SizedBox(
                          height: _getSize.height * 0.02,
                        ),
                        CustomInput2(
                          label: 'Access code',
                          hint: 'Enter access code',
                          onChanged: (v) {
                            code = v!;
                          },
                          onSaved: (value) {
                            print(value);
                            code = value!;
                          },
                        ),
                        SizedBox(
                          height: _getSize.height * 0.05,
                        ),
                        ButtonWithFuction(
                            text: "Continue",
                            onPressed: () {
                              // print(code);

                              AccessCodeUtil.accessCode(
                                  _codeFormKey, context, code);
                         
                            }),
                        SizedBox(
                          height: _getSize.height * 0.3,
                        ),
                        // Column(
                        //   children: [
                        //     Row(
                        //       children: [
                        //         Container(
                        //           color: Pallete.fade,
                        //           width: _getSize.width * 0.17,
                        //           height: _getSize.height * 0.0005,
                        //         ),
                        //         const Text("  Don't have a code tenant? "),
                        //         Container(
                        //           color: Pallete.fade,
                        //           width: _getSize.width * 0.17,
                        //           height: _getSize.height * 0.0005,
                        //         ),
                        //       ],
                        //     ),
                        //     SizedBox(
                        //       height: _getSize.height * 0.03,
                        //     ),
                        //     Text(
                        //       "Contact Abja properties",
                        //       style: AppFonts.body1.copyWith(
                        //           fontSize: 14,
                        //           fontWeight: FontWeight.w600,
                        //           color: Pallete.text),
                        //     ), SizedBox(
                        //       height: _getSize.height * 0.02,
                        //     ),
                        //     Padding(
                        //       padding: const EdgeInsets.symmetric(
                        //           vertical: 8.0, horizontal: 16),
                        //       child: Row(
                        //         mainAxisAlignment: MainAxisAlignment.spaceAround,
                        //         children: [
                        //           Image.asset(
                        //             AppImages.inbox,
                        //             width: _getSize.width * 0.05,
                        //           ),
                        //           Image.asset(
                        //             AppImages.support,
                        //             width: _getSize.width * 0.05,
                        //           ),

                        //         ],
                        //       ),
                        //     ),
                        //     SizedBox(height: _getSize.height * 0.02),
                        //     Row(
                        //       children: [
                        //         Container(
                        //           color: Pallete.fade,
                        //          width: _getSize.width * 0.38,
                        //           height: _getSize.height * 0.0005,
                        //         ),
                        //         const Text("  Or  "),
                        //         Container(
                        //           color: Pallete.fade,
                        //          width: _getSize.width * 0.38,
                        //           height: _getSize.height * 0.0005,
                        //         ),
                        //       ],
                        //     )
                        //   ],
                        // ),
                        // SizedBox(height: _getSize.height * 0.02),

                        GestureDetector(
                          onTap: () => {
                            Navigator.of(context)
                                .pushNamed(AppRoutes.getCodeScreen)
                          },
                          child: Row(
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: [
                              Text(
                                'Do not have an access code? ',
                                style: AppFonts.bodyText.copyWith(
                                    color: Pallete.fade,
                                    fontWeight: FontWeight.w600,
                                    fontSize: 14),
                              ),
                              Text(
                                'Click here',
                                style: AppFonts.boldText.copyWith(
                                    fontWeight: FontWeight.bold,
                                    color: Pallete.secondaryColor,
                                    fontSize: 14),
                              ),
                            ],
                          ),
                        ),  SizedBox(
                          height: _getSize.height * 0.05,
                        ), const LoginNavigation(
                    text2: "Already have an account? ",
                    text: 'Login',
                    dir: AppRoutes.loginScreen,
                  )
                      ],
                    ),
                  ),
                ),
              ],
            ),
          ),
        ));
  }
}
